version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: kcau
      POSTGRES_PASSWORD: kcau_pass
      POSTGRES_DB: kcau_lms
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: sh -c "python manage.py migrate --noinput && python manage.py seed_data && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=kcau_lms
      - DATABASE_USER=kcau
      - DATABASE_PASSWORD=kcau_pass
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  db_data:
