# Generated by Django 4.2.9 on 2026-03-02 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('time', models.CharField(blank=True, max_length=100)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('LECTURER', 'LECTURER'), ('STUDENT', 'STUDENT')], default='STUDENT', max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('reg_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('enrolled_count', models.IntegerField(default=0)),
                ('completion_percent', models.IntegerField(default=0)),
                ('lecturer', models.ForeignKey(blank=True, limit_choices_to={'role': 'LECTURER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.userprofile')),
            ],
        ),
    ]
