# Generated by Django 4.2.13 on 2026-03-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_coursematerial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='file_url',
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
