# Generated by Django 5.2.12 on 2026-03-11 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_department_course_unit_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meeting_url', models.URLField()),
                ('meeting_code', models.CharField(blank=True, max_length=100)),
                ('scheduled_for', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_classes', to='lms.course')),
                ('host', models.ForeignKey(blank=True, limit_choices_to={'role': 'LECTURER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.userprofile')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
    ]
