# Generated by Django 5.2.12 on 2026-03-11 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_lecturerplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('entry_type', models.CharField(choices=[('CLASS', 'Scheduled Class'), ('ASSIGNMENT', 'Assignment Deadline'), ('CAT', 'CAT / Test'), ('PERSONAL', 'Personal Plan'), ('EXAM', 'Exam')], default='PERSONAL', max_length=20)),
                ('entry_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_timetable_entries', to='lms.course')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='lms.userprofile')),
            ],
            options={
                'ordering': ['entry_date', 'start_time'],
            },
        ),
    ]
